"""
ComposeGenerator v2: Generates docker-compose.yml with app, sidecar, and
optional database services (postgres, mysql, redis, mongodb, etc).
"""

from pathlib import Path

from containerforge.generator.db_wirer import (
    render_app_env_additions,
    render_db_services,
    render_db_volumes,
    render_depends_on,
)


class ComposeGenerator:
    def __init__(self, app_path, app_info, name, tag="latest",
                 sidecar_port=9090, databases=None, config=None):
        self.app_path = Path(app_path)
        self.info = app_info
        self.name = name
        self.tag = tag
        self.sidecar_port = sidecar_port
        self.config = config
        # databases: explicit list > auto-detect
        if databases is not None:
            self.databases = databases
        elif config and config.databases:
            self.databases = config.databases
        else:
            self.databases = []

    def generate(self) -> Path:
        compose_path = self.app_path / "docker-compose.yml"
        compose_path.write_text(self._build())
        return compose_path

    def _build(self) -> str:
        port = self.info.get("port", 8000)
        name = self.name
        has_env = self.info.get("has_env_file", False)
        lang = self.info.get("language", "python")

        env_file_line = "    env_file:\n      - .env\n" if has_env else ""

        # DB connection env vars for the app
        db_env_lines = render_app_env_additions(self.databases)
        db_depends = render_depends_on(self.databases)
        db_services_block = render_db_services(self.databases)
        db_volumes_block = render_db_volumes(self.databases)

        # Language-specific env
        lang_env = ""
        if lang == "python":
            lang_env = "      - PYTHONUNBUFFERED=1\n      - PYTHONDONTWRITEBYTECODE=1\n"
        elif lang == "nodejs":
            lang_env = "      - NODE_ENV=production\n"

        depends_block = ""
        if db_depends:
            depends_block = f"    depends_on:\n{db_depends}\n"

        volumes_section = "volumes:"
        if db_volumes_block:
            volumes_section = f"volumes:\n{db_volumes_block}"

        return f"""\
# ─────────────────────────────────────────────────────────────────────
# ContainerForge — docker-compose.yml
# App: {name}  |  Port: {port}
# Generated by ContainerForge — https://github.com/containerforge/containerforge
# ─────────────────────────────────────────────────────────────────────

services:

  # ── Application ───────────────────────────────────────────────────
  {name}:
    build:
      context: .
      dockerfile: Dockerfile
    image: {name}:{self.tag}
    container_name: {name}
    restart: unless-stopped
    ports:
      - "{port}:{port}"
    environment:
      - PORT={port}
{lang_env}{db_env_lines}
{env_file_line}{depends_block}    networks:
      - forge-net
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:{port}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # ── ContainerForge Sidecar Watchdog ───────────────────────────────
  sidecar:
    build:
      context: .
      dockerfile: Dockerfile.sidecar
    container_name: {name}-sidecar
    restart: unless-stopped
    ports:
      - "{self.sidecar_port}:{self.sidecar_port}"
    environment:
      - TARGET_URL=http://{name}:{port}
      - CONTAINER_NAME={name}
      - WATCH_INTERVAL=10
      - FAILURE_THRESHOLD=3
      - RESTART_ENABLED=true
      - SIDECAR_PORT={self.sidecar_port}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      {name}:
        condition: service_healthy
    networks:
      - forge-net
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:{self.sidecar_port}/health"]
      interval: 20s
      timeout: 5s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"

{db_services_block}
networks:
  forge-net:
    driver: bridge

{volumes_section}
"""
