"""
GrafanaGenerator: Generates a pre-built Grafana dashboard JSON
that visualizes all ContainerForge sidecar Prometheus metrics out of the box.

Dashboard panels:
  - Container health status (gauge)
  - Availability % (stat)
  - Request rate (time series)
  - Error rate % (time series)  
  - Avg latency ms (time series)
  - Memory usage MB (time series)
  - CPU % (time series)
  - Restart count (stat)
  - Health check history (table)
  - Uptime (stat)
"""

import json
from pathlib import Path
from datetime import datetime


class GrafanaGenerator:
    def __init__(self, app_path: Path, config, detection: dict):
        self.app_path = Path(app_path)
        self.cfg = config
        self.d = detection
        self.name = config.name or app_path.name.lower().replace("_", "-")

    def generate(self) -> Path:
        out_dir = self.app_path / ".containerforge"
        out_dir.mkdir(exist_ok=True)

        dashboard = self._build_dashboard()
        out_path = out_dir / "grafana-dashboard.json"
        out_path.write_text(json.dumps(dashboard, indent=2))

        # Also generate a provisioning config
        prov_path = out_dir / "grafana-provisioning.yml"
        prov_path.write_text(self._provisioning_config())

        # Docker compose snippet to add Grafana
        compose_path = out_dir / "grafana-compose-snippet.yml"
        compose_path.write_text(self._compose_snippet())

        return out_path

    def _build_dashboard(self) -> dict:
        container = self.name
        sidecar_port = self.cfg.sidecar_port
        app_port = self.d.get("port", 8080)
        lang = self.d.get("language_display", self.d.get("language", "app"))
        fw = self.d.get("framework_display", self.d.get("framework", ""))

        return {
            "id": None,
            "uid": f"containerforge-{container}",
            "title": f"ContainerForge — {container}",
            "description": f"Auto-generated by ContainerForge | {lang}/{fw}",
            "tags": ["containerforge", container, lang],
            "timezone": "browser",
            "schemaVersion": 38,
            "version": 1,
            "refresh": "30s",
            "time": {"from": "now-1h", "to": "now"},
            "templating": {
                "list": [
                    {
                        "name": "container",
                        "type": "constant",
                        "query": container,
                        "current": {"value": container, "text": container},
                        "hide": 2,
                    }
                ]
            },
            "annotations": {"list": []},
            "panels": self._panels(container),
            "__inputs": [
                {
                    "name": "DS_PROMETHEUS",
                    "label": "Prometheus",
                    "type": "datasource",
                    "pluginId": "prometheus",
                    "pluginName": "Prometheus",
                }
            ],
            "__requires": [
                {"type": "grafana", "id": "grafana", "name": "Grafana", "version": "10.0.0"},
                {"type": "datasource", "id": "prometheus", "name": "Prometheus", "version": "1.0.0"},
            ],
        }

    def _panels(self, container: str) -> list:
        # Grid layout: 24 cols total
        panels = []
        pid = 1

        def stat(title, expr, unit="short", thresholds=None, x=0, y=0, w=4, h=4):
            nonlocal pid
            p = {
                "id": pid, "type": "stat", "title": title,
                "gridPos": {"x": x, "y": y, "w": w, "h": h},
                "targets": [{"expr": expr, "legendFormat": title, "datasource": "${DS_PROMETHEUS}"}],
                "options": {
                    "reduceOptions": {"calcs": ["lastNotNull"]},
                    "orientation": "auto",
                    "colorMode": "background",
                },
                "fieldConfig": {
                    "defaults": {
                        "unit": unit,
                        "thresholds": thresholds or {
                            "mode": "absolute",
                            "steps": [{"color": "green", "value": None}],
                        },
                    }
                },
            }
            pid += 1
            return p

        def timeseries(title, targets, unit="short", x=0, y=0, w=12, h=8):
            nonlocal pid
            p = {
                "id": pid, "type": "timeseries", "title": title,
                "gridPos": {"x": x, "y": y, "w": w, "h": h},
                "targets": [
                    {"expr": t[0], "legendFormat": t[1], "datasource": "${DS_PROMETHEUS}"}
                    for t in targets
                ],
                "options": {"tooltip": {"mode": "multi"}, "legend": {"displayMode": "list"}},
                "fieldConfig": {
                    "defaults": {"unit": unit, "custom": {"lineWidth": 2, "fillOpacity": 10}},
                },
            }
            pid += 1
            return p

        def gauge(title, expr, min_val=0, max_val=100, unit="percent", x=0, y=0, w=4, h=4):
            nonlocal pid
            p = {
                "id": pid, "type": "gauge", "title": title,
                "gridPos": {"x": x, "y": y, "w": w, "h": h},
                "targets": [{"expr": expr, "legendFormat": title, "datasource": "${DS_PROMETHEUS}"}],
                "options": {"reduceOptions": {"calcs": ["lastNotNull"]}},
                "fieldConfig": {
                    "defaults": {
                        "unit": unit, "min": min_val, "max": max_val,
                        "thresholds": {
                            "mode": "absolute",
                            "steps": [
                                {"color": "red", "value": None},
                                {"color": "yellow", "value": 85},
                                {"color": "green", "value": 99},
                            ],
                        },
                    }
                },
            }
            pid += 1
            return p

        # Row 1: Status stats (y=0)
        panels.append(stat(
            "Health Status",
            f'cf_target_up{{container="{container}"}}',
            thresholds={"mode": "absolute", "steps": [
                {"color": "red", "value": None}, {"color": "green", "value": 1}
            ]},
            x=0, y=0, w=4, h=4,
        ))
        panels.append(gauge(
            "Availability",
            f'cf_availability_percent{{container="{container}"}}',
            x=4, y=0, w=4, h=4,
        ))
        panels.append(stat(
            "Total Requests",
            f'cf_app_requests_total{{container="{container}"}}',
            unit="short", x=8, y=0, w=4, h=4,
        ))
        panels.append(stat(
            "Errors",
            f'cf_app_errors_total{{container="{container}"}}',
            unit="short",
            thresholds={"mode": "absolute", "steps": [
                {"color": "green", "value": None}, {"color": "yellow", "value": 1}, {"color": "red", "value": 10}
            ]},
            x=12, y=0, w=4, h=4,
        ))
        panels.append(stat(
            "Avg Latency",
            f'cf_app_avg_latency_ms{{container="{container}"}}',
            unit="ms", x=16, y=0, w=4, h=4,
        ))
        panels.append(stat(
            "Restarts",
            f'cf_restarts_total{{container="{container}"}}',
            thresholds={"mode": "absolute", "steps": [
                {"color": "green", "value": None}, {"color": "yellow", "value": 1}, {"color": "red", "value": 3}
            ]},
            x=20, y=0, w=4, h=4,
        ))

        # Row 2: Time series (y=4)
        panels.append(timeseries(
            "Request Rate",
            [(f'rate(cf_app_requests_total{{container="{container}"}}[5m])', "req/s")],
            unit="reqps", x=0, y=4, w=12, h=8,
        ))
        panels.append(timeseries(
            "Error Rate %",
            [(f'100 * cf_app_errors_total{{container="{container}"}} / clamp_min(cf_app_requests_total{{container="{container}"}}, 1)', "error %")],
            unit="percent", x=12, y=4, w=12, h=8,
        ))

        # Row 3: Resources (y=12)
        panels.append(timeseries(
            "Memory Usage",
            [(f'cf_app_memory_mb{{container="{container}"}}', "used MB")],
            unit="megabytes", x=0, y=12, w=12, h=8,
        ))
        panels.append(timeseries(
            "CPU Usage",
            [(f'cf_app_cpu_percent{{container="{container}"}}', "cpu %")],
            unit="percent", x=12, y=12, w=12, h=8,
        ))

        # Row 4: Sidecar stats (y=20)
        panels.append(timeseries(
            "Health Check Failures",
            [(f'rate(cf_failures_total{{container="{container}"}}[5m])', "failures/s")],
            unit="short", x=0, y=20, w=12, h=6,
        ))
        panels.append(stat(
            "Sidecar Uptime",
            "cf_sidecar_uptime_seconds",
            unit="s", x=12, y=20, w=6, h=6,
        ))
        panels.append(stat(
            "Total Health Checks",
            f'cf_checks_total{{container="{container}"}}',
            unit="short", x=18, y=20, w=6, h=6,
        ))

        return panels

    def _provisioning_config(self) -> str:
        return f"""\
# Grafana dashboard provisioning config
# Place this in grafana/provisioning/dashboards/containerforge.yml

apiVersion: 1

providers:
  - name: ContainerForge
    orgId: 1
    type: file
    disableDeletion: false
    updateIntervalSeconds: 30
    allowUiUpdates: true
    options:
      path: /var/lib/grafana/dashboards
      foldersFromFilesStructure: false
"""

    def _compose_snippet(self) -> str:
        sidecar_port = self.cfg.sidecar_port
        return f"""\
# Add this to your docker-compose.yml to enable Grafana + Prometheus monitoring

  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=15d
    networks:
      - forge-net

  grafana:
    image: grafana/grafana:10.4.0
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./.containerforge/grafana-dashboard.json:/var/lib/grafana/dashboards/containerforge.json:ro
      - ./.containerforge/grafana-provisioning.yml:/etc/grafana/provisioning/dashboards/containerforge.yml:ro
    depends_on:
      - prometheus
    networks:
      - forge-net

# Add to volumes section:
#   prometheus_data:
#   grafana_data:

---
# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: containerforge-sidecar
    static_configs:
      - targets: ['sidecar:{sidecar_port}']
    metrics_path: /sidecar/metrics
"""
