"""
ConfigLoader: Reads and validates containerforge.yml from an app directory.

When present, containerforge.yml overrides auto-detection for everything.
Teams commit this file to version control for reproducible containerization.

Example containerforge.yml:
  name: my-api
  port: 5000
  lang: python
  framework: flask
  tag: v1.2.3
  platform: linux/amd64
  sidecar_port: 9090
  inject_health: true
  databases:
    - postgres
    - redis
  env_secrets:
    - DATABASE_URL
    - SECRET_KEY
  push_registry: docker.io/myorg
  k8s:
    namespace: production
    replicas: 3
    ingress: true
  cloud:
    provider: aws
    region: us-east-1
"""

import yaml
from pathlib import Path
from dataclasses import dataclass, field
from typing import Optional

CONFIG_FILENAME = "containerforge.yml"

DEFAULTS = {
    "name": None,
    "port": None,
    "lang": "auto",
    "framework": None,
    "tag": "latest",
    "platform": "linux/amd64",
    "sidecar_port": 9090,
    "inject_health": True,
    "databases": [],
    "env_secrets": [],
    "push_registry": None,
    "scan": True,
    "sbom": False,
    "k8s": {},
    "cloud": {},
    "labels": {},
}


@dataclass
class ForgeConfig:
    # Core
    name: Optional[str] = None
    port: Optional[int] = None
    lang: str = "auto"
    framework: Optional[str] = None
    tag: str = "latest"
    platform: str = "linux/amd64"

    # Features
    sidecar_port: int = 9090
    inject_health: bool = True
    scan: bool = True
    sbom: bool = False

    # Databases
    databases: list = field(default_factory=list)

    # Secrets
    env_secrets: list = field(default_factory=list)

    # Registry
    push_registry: Optional[str] = None

    # Kubernetes
    k8s_namespace: str = "default"
    k8s_replicas: int = 2
    k8s_ingress: bool = False
    k8s_ingress_host: Optional[str] = None
    k8s_hpa: bool = False
    k8s_min_replicas: int = 1
    k8s_max_replicas: int = 10

    # Cloud
    cloud_provider: Optional[str] = None
    cloud_region: Optional[str] = None

    # Extra labels
    labels: dict = field(default_factory=dict)

    # Source path (runtime, not from yaml)
    source: str = "."


def load_config(app_path: Path) -> ForgeConfig:
    """
    Load containerforge.yml if present, return ForgeConfig.
    Falls back to all defaults if file not found.
    """
    config_path = app_path / CONFIG_FILENAME
    raw = {}

    if config_path.exists():
        try:
            text = config_path.read_text()
            raw = yaml.safe_load(text) or {}
        except Exception as e:
            print(f"[warn] Could not parse {CONFIG_FILENAME}: {e}")

    k8s = raw.pop("k8s", {}) or {}
    cloud = raw.pop("cloud", {}) or {}

    cfg = ForgeConfig(
        name=raw.get("name"),
        port=raw.get("port"),
        lang=raw.get("lang", "auto"),
        framework=raw.get("framework"),
        tag=raw.get("tag", "latest"),
        platform=raw.get("platform", "linux/amd64"),
        sidecar_port=int(raw.get("sidecar_port", 9090)),
        inject_health=bool(raw.get("inject_health", True)),
        scan=bool(raw.get("scan", True)),
        sbom=bool(raw.get("sbom", False)),
        databases=raw.get("databases", []),
        env_secrets=raw.get("env_secrets", []),
        push_registry=raw.get("push_registry"),
        labels=raw.get("labels", {}),

        # k8s sub-section
        k8s_namespace=k8s.get("namespace", "default"),
        k8s_replicas=int(k8s.get("replicas", 2)),
        k8s_ingress=bool(k8s.get("ingress", False)),
        k8s_ingress_host=k8s.get("ingress_host"),
        k8s_hpa=bool(k8s.get("hpa", False)),
        k8s_min_replicas=int(k8s.get("min_replicas", 1)),
        k8s_max_replicas=int(k8s.get("max_replicas", 10)),

        # cloud sub-section
        cloud_provider=cloud.get("provider"),
        cloud_region=cloud.get("region"),

        source=str(app_path),
    )
    return cfg


def generate_example_config(detection: dict, app_path: Path) -> str:
    """Generate a starter containerforge.yml based on detection results."""
    port = detection.get("port", 8080)
    lang = detection.get("language", "python")
    fw = detection.get("framework", "unknown")
    name = app_path.name.lower().replace("_", "-")

    dbs = _guess_databases(detection)

    lines = [
        f"# ContainerForge configuration — commit this to version control",
        f"# Generated by: containerforge init",
        f"",
        f"name: {name}",
        f"lang: {lang}",
        f"framework: {fw}",
        f"port: {port}",
        f"tag: latest",
        f"platform: linux/amd64",
        f"",
        f"# Observability sidecar",
        f"sidecar_port: 9090",
        f"inject_health: true",
        f"",
        f"# Security scanning (requires trivy)",
        f"scan: true",
        f"sbom: false",
        f"",
        f"# Databases (auto-detected or add manually)",
        f"databases:",
    ]
    for db in dbs:
        lines.append(f"  - {db}")
    if not dbs:
        lines.append(f"  # - postgres")
        lines.append(f"  # - redis")

    lines += [
        f"",
        f"# Secrets to inject as env vars (values from .env or environment)",
        f"env_secrets:",
        f"  # - DATABASE_URL",
        f"  # - SECRET_KEY",
        f"",
        f"# Kubernetes output (containerforge k8s ./app)",
        f"k8s:",
        f"  namespace: default",
        f"  replicas: 2",
        f"  ingress: false",
        f"  # ingress_host: myapp.example.com",
        f"  hpa: false",
        f"  min_replicas: 1",
        f"  max_replicas: 10",
        f"",
        f"# Cloud deployment (containerforge deploy ./app)",
        f"cloud:",
        f"  # provider: aws   # aws | gcp | azure",
        f"  # region: us-east-1",
        f"  # push_registry: docker.io/myorg",
        f"",
        f"# Extra OCI labels",
        f"labels:",
        f"  # org.opencontainers.image.source: https://github.com/myorg/{name}",
    ]

    return "\n".join(lines) + "\n"


def _guess_databases(detection: dict) -> list:
    """Guess databases from dependencies or env vars."""
    deps_text = ""
    env_vars = detection.get("env_vars", [])
    combined = " ".join(env_vars).lower()

    guessed = []
    db_signals = {
        "postgres": ["postgres", "pg", "psycopg", "asyncpg", "DATABASE_URL"],
        "mysql": ["mysql", "mysqlclient", "pymysql"],
        "redis": ["redis", "REDIS_URL", "CACHE_URL"],
        "mongodb": ["pymongo", "motor", "MONGO_URL", "MONGODB_URI"],
        "sqlite": ["sqlite"],
    }
    for db, signals in db_signals.items():
        if any(s.lower() in combined for s in signals):
            guessed.append(db)
    return guessed
